CREATE TABLE IF NOT EXISTS Role (
  RoleId VARCHAR(20) PRIMARY KEY,
  RoleName NVARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Employee (
  EmployeeId VARCHAR(20) PRIMARY KEY,
  FullName NVARCHAR(100) NOT NULL,
  Phone VARCHAR(20),
  Email VARCHAR(100) NOT NULL UNIQUE,
  Username NVARCHAR(50) NOT NULL UNIQUE,
  PasswordHash VARCHAR(255) NOT NULL,
  RoleId VARCHAR(20) NOT NULL,
  IsActive INTEGER NOT NULL DEFAULT 1,
  FOREIGN KEY (RoleId) REFERENCES Role(RoleId)
);

CREATE TABLE IF NOT EXISTS Customer (
  CustomerId VARCHAR(20) PRIMARY KEY,
  CustomerName NVARCHAR(100) NOT NULL,
  Phone VARCHAR(20) NOT NULL UNIQUE,
  Gender NVARCHAR(10),
  Email VARCHAR(100),
  DateOfBirth DATE,
  Address NVARCHAR(255),
  TotalSpent DECIMAL(18,2) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS MedicineCategory (
  CategoryId VARCHAR(30) PRIMARY KEY,
  CategoryName NVARCHAR(150) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS Medicine (
  MedicineId VARCHAR(30) PRIMARY KEY,
  MedicineName NVARCHAR(200) NOT NULL,
  CategoryId VARCHAR(30),
  ProductType NVARCHAR(50) NOT NULL,
  UnitName NVARCHAR(50) NOT NULL,
  DrugRegistrationCode NVARCHAR(80),
  CostPrice DECIMAL(18,2) NOT NULL DEFAULT 0,
  SalePrice DECIMAL(18,2) NOT NULL DEFAULT 0,
  MedicineStatus NVARCHAR(30) NOT NULL DEFAULT 'Đang kinh doanh',
  Ingredient NVARCHAR(500),
  Usage NVARCHAR(500),
  Dosage NVARCHAR(500),
  FOREIGN KEY (CategoryId) REFERENCES MedicineCategory(CategoryId)
);

CREATE TABLE IF NOT EXISTS MedicineStock (
  MedicineId VARCHAR(30) PRIMARY KEY,
  QuantityOnHand INTEGER NOT NULL DEFAULT 0,
  FOREIGN KEY (MedicineId) REFERENCES Medicine(MedicineId) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS StockAlert (
  AlertId VARCHAR(30) PRIMARY KEY,
  MedicineId VARCHAR(30) NOT NULL,
  Stock INTEGER NOT NULL,
  MinStock INTEGER NOT NULL DEFAULT 10,
  Note NVARCHAR(500),
  Status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  CreatedBy NVARCHAR(100),
  CreatedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ResolvedAt DATETIME,
  ResolutionType VARCHAR(30),
  ResolutionNote NVARCHAR(500),
  FOREIGN KEY (MedicineId) REFERENCES Medicine(MedicineId) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS SalesInvoice (
  InvoiceId VARCHAR(30) PRIMARY KEY,
  EmployeeId VARCHAR(20),
  CustomerId VARCHAR(20),
  CustomerNameSnapshot NVARCHAR(100) NOT NULL,
  PhoneSnapshot VARCHAR(20),
  InvoiceDate DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  TotalAmount DECIMAL(18,2) NOT NULL DEFAULT 0,
  Status NVARCHAR(30) NOT NULL DEFAULT 'Hoàn thành',
  FOREIGN KEY (EmployeeId) REFERENCES Employee(EmployeeId),
  FOREIGN KEY (CustomerId) REFERENCES Customer(CustomerId)
);

CREATE TABLE IF NOT EXISTS SalesInvoiceLine (
  LineId VARCHAR(30) PRIMARY KEY,
  InvoiceId VARCHAR(30) NOT NULL,
  MedicineId VARCHAR(30) NOT NULL,
  MedicineNameSnapshot NVARCHAR(200) NOT NULL,
  UnitSnapshot NVARCHAR(50) NOT NULL,
  Quantity INTEGER NOT NULL,
  UnitPrice DECIMAL(18,2) NOT NULL,
  LineTotal DECIMAL(18,2) NOT NULL,
  FOREIGN KEY (InvoiceId) REFERENCES SalesInvoice(InvoiceId) ON DELETE CASCADE,
  FOREIGN KEY (MedicineId) REFERENCES Medicine(MedicineId)
);
